name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      

      - name: Build application
        run: msbuild /p:Configuration=Release C:Users/micha/Downloads/Github repost/Michaeleah-CI-CD-pipeline/SLD521FA2Michaeleah/SLD521 FA2 Michaeleah-Anne Murray.sln

  test:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
       
          

      - name: Build application
        run: msbuild /p:Configuration=Release C:Users/micha/Downloads/Github repost/Michaeleah-CI-CD-pipeline/SLD521FA2Michaeleah/SLD521 FA2 Michaeleah-Anne Murray.sln

      - name: Run tests (replace with actual test commands)
        run: echo "Running tests..."

  deploy:
    needs: test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      

      - name: Build application
        run: msbuild /p:Configuration=Release C:Users/micha/Downloads/Github repost/Michaeleah-CI-CD-pipeline/SLD521FA2Michaeleah/SLD521 FA2 Michaeleah-Anne Murray.sln

      - name: Deploy to staging (replace with actual deployment steps)
        run: echo "Deploying to staging..."
